models.py
# coding: utf-8
from init import db


class Book(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255), unique=True, nullable=False)
    author = db.Column(db.String(255), nullable=True)
    page_count = db.Column(db.Integer, nullable=True)
    pub_date = db.Column(db.Date, nullable=True)

    def __unicode__(self):
        return u'%s' % self.title

modules/api/forms.py
# coding: utf-8
from wtforms import Form
from wtforms.fields.core import StringField, IntegerField, DateField
from wtforms.validators import InputRequired, Optional


class BookForm(Form):
    title = StringField(validators=[InputRequired()])
    author = StringField(validators=[Optional()])
    page_count = IntegerField(validators=[Optional()])
    pub_date = DateField(validators=[Optional()], format='%d.%m.%Y', render_kw={'placeholder': 'dd.mm.yyyy'})

main.py
# coding: utf-8
from flask import render_template, request
from init import app, db
import models
from modules.api.forms import BookForm


@app.route('/')
def index():
    context = {
        'page_title': u'Main page',
        'form': BookForm()
    }
    try:
        context['limit'] = int(request.args.get('limit', 10))
        if context['limit'] > 10:
            context['limit'] = 50
    except ValueError:
        context['limit'] = 10
    try:
        context['offset'] = int(request.args.get('offset', 0))
        if context['offset'] < 0:
            context['offset'] = 0
    except ValueError:
        context['offset'] = 0
    context['books'] = db.session.query(models.Book).order_by(models.Book.title).offset(context['offset']).limit(context['limit'])
    return render_template('index.html', **context)


from modules.api.views import mod as api_mod
app.register_blueprint(api_mod)


if __name__ == "__main__":
    app.run(debug=True, port=5000)

modules/__init__.py
__author__ = 'strange'

modules/api/__init__.py
__author__ = 'strange'

modules/api/views.py
# coding: utf-8
import sqlite3
from flask import Blueprint, jsonify, request
from sqlalchemy.orm.exc import NoResultFound
from models import db, Book
from . import forms

mod = Blueprint('api', __name__, url_prefix='/api')


def get_book(title):
    try:
        book = db.session.query(Book).filter(Book.title == title).one()
    except NoResultFound:
        return {}, 404
    return {
        'id': book.id,
        'title': book.title,
        'author': book.author,
        'page_count': book.page_count,
        'pub_date': str(book.pub_date),
    }, 200


def create_book(data):
    form = forms.BookForm(data)
    if form.validate():
        book = Book(
            title=form.title.data,
            author=form.author.data,
            page_count=form.page_count.data,
            pub_date=form.pub_date.data,
        )
        db.session.add(book)
        try:
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            return {
                'title': ['The book already exists'],
            }, 412
        return {
            'id': book.id,
            'title': book.title,
            'author': book.author,
            'page_count': book.page_count,
            'pub_date': str(book.pub_date),
        }, 201
    result = form.errors
    return result, 412


def update_book(data):
    try:
        book = db.session.query(Book).filter(Book.id == data.get('id')).one()
    except NoResultFound:
        return {}, 404
    form = forms.BookForm(data)
    if form.validate():
        book.title = form.title.data
        book.author = form.author.data
        book.page_count = form.page_count.data
        book.pub_date = form.pub_date.data
        try:
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            return {
                'title': ['The book with title already exists'],
            }, 412
        return {}, 204
    result = form.errors
    return result, 412


def delete_book(title):
    try:
        book = db.session.query(Book).filter(Book.title == title).one()
    except NoResultFound:
        return {}, 404
    db.session.delete(book)
    db.session.commit()
    return {}, 204


@mod.route('/book/', methods=['GET', 'POST', 'PUT', 'DELETE'])
def book():
    if request.method == 'GET':
        response = get_book(request.args.get('title'))
        return jsonify(response[0]), response[1]
    if request.method == 'POST':
        response = create_book(request.form.copy())
        return jsonify(response[0]), response[1]
    if request.method == 'PUT':
        response = update_book(request.form.copy())
        return jsonify(response[0]), response[1]
    if request.method == 'DELETE':
        response = delete_book(request.form.get('title'))
        return jsonify(response[0]), response[1]
    return '', 405

templates/api/book/form.html
<h2>Add book</h2>
<form action="{{ url_for('api.book') }}" method="post" id="form-book-add">
    {% for name, field in form._fields.items() %}
        <div class="form-group" data-field="{{ name }}">
            {{ field.label }}
            {{ field(class='form-control') }}
            <p class="text-danger" style="display: none;"></p>
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-default">Send</button>
</form>

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <title>{{ page_title }}</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap-theme.min.css"/>
</head>
<body>
    <div class="container">
        {% block main %}
        {% endblock %}
    </div>
<script type="text/javascript" src="/static/js/jquery-1.12.1.min.js"></script>
<script type="text/javascript" src="/static/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/static/js/script.js"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block main %}
    <h1>Книги</h1>
    <table class="table" id="books-table">
        <thead>
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Author</th>
                <th>Page count</th>
                <th>Date of publication</th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
                <tr>
                    <td>{{ book.id }}</td>
                    <td>{{ book.title }}</td>
                    <td>{{ book.author }}</td>
                    <td>{{ book.page_count }}</td>
                    <td>{{ book.pub_date }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <hr/>
    {% include 'api/book/form.html' %}
{% endblock %}